
[MeasureLine1]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine2]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine3]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine4]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine5]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine6]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine7]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine8]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine9]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine10]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine11]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine12]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine13]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine14]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures

[MeasureLine15]
Measure=Plugin
Plugin=PluginClipboard
IfMatch=^$
DynamicVariables=1
Group=ClipMeasures