;[Variables]
;Font=Seoge UI
;BoxW=500
;BoxH=60
;Color=23,23,23
;Hightlight=70,70,70
;Animated=0
;Dismisser=0
;Maximum_Desktop=8
;Corner=0
;; Max = 8

;OnOff=Off
;Edge=0
;;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;;║ METERSTYLES                                                                                          ║
;;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝

;[BoldText]
;FontFace=#Font#
;FontWeight=800
;AntiAlias=1
;#Fontcolor#
;FontSize=15
;H=20
;SolidColor=0,0,0,1
;StringALign=LeftCenter

;[SemiBoldedText]
;FontFace=#Font#
;FontWeight=500
;AntiAlias=1
;#Fontcolor#
;FontSize=12
;H=12
;SolidColor=0,0,0,1
;StringALign=LeftCenter

;[RegularText]
;FontFace=#Font#
;AntiAlias=1
;#Fontcolor#
;FontSize=12
;H=12
;SolidColor=0,0,0,1
;StringALign=LeftCenter
[Variables]
Edge=0
Corner=0
