;——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[Variables]
;——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

GlobalW=400
GlobalH=100
Alpha=150
engine=https://www.google.com/search?q=
enginename=Google
browserlink=["#engine#[Filter2]"]
browser=Default
dictlink=https://dictionary.cambridge.org/dictionary/english-chinese-traditional/
Icon=1
Animated=0
Animation=0
AnimatedA=255

OnOff=1
@includeGlobal=#@#GlobalVars.inc

H1=-,
H2=-m,
H3=shell:AppsFolder
H4=-,
H5=-L
H6=-L
H7=shutdown -s
H8=-confiog
H9=-config
H10=explorer.exe
H11=ss
H12=powershell
H13=This
H14=rl
H15=config
;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝

[BoldText]
FontFace=#Font#
FontWeight=800
AntiAlias=1
FontColor=#FontColor#
FontSize=12
StringALign=LeftCenter

[SemiBoldText]
FontFace=#Font#
FontWeight=500
AntiAlias=1
FontColor=#FontColor#
FontSize=12
StringALign=LeftCenter

[RegularText]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=12
StringALign=LeftCenter
