;——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[Variables]
;——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

GlobalW=400
GlobalH=100
Alpha=150
engine=https://www.google.com/search?q=
enginename=Google
browserlink=["#engine#[Filter2]"]
browser=Default
dictlink=https://dictionary.cambridge.org/dictionary/english-chinese-traditional/
Icon=1
Animated=1
Animation=-100
AnimatedA=0

OnOff=1
@includeGlobal=#@#GlobalVars.inc

H1=-,
H2=-L
H3=-L
H4=shutdown -s
H5=-confiog
H6=-config
H7=explorer.exe
H8=ss
H9=powershell
H10=This
H11=rl
H12=config
H13=C:\Users\Jax4Real\AppData\Roaming
H14=ms-clock:
H15=ms-settings:bluetooth
;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝

[BoldText]
FontFace=#Font#
FontWeight=800
AntiAlias=1
FontColor=#FontColor#
FontSize=12
StringALign=LeftCenter

[SemiBoldText]
FontFace=#Font#
FontWeight=500
AntiAlias=1
FontColor=#FontColor#
FontSize=12
StringALign=LeftCenter

[RegularText]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=12
StringALign=LeftCenter
