;——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[Variables]
;——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

GlobalW=400
GlobalH=100
Alpha=150
engine=https://www.google.com/search?q=
enginename=Google
browserlink=["#engine#[Filter2]"]
browser=Default
dictlink=https://dictionary.cambridge.org/dictionary/english-chinese-traditional/
Icon=1
Animated=1
Animation=-100
AnimatedA=0

OnOff=1
@includeGlobal=#@#GlobalVars.inc

H1=-k
H2=-search
H3=-search
H4=
H5=
H6=-e
H7==s
H8=l
H9=l
H10=C:\Users\Jax4Real\AppData\Roaming
H11=-
H12=-e
H13=-d
H14=powershell -s
H15=powershell
;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝

[BoldText]
FontFace=#Font#
FontWeight=800
AntiAlias=1
FontColor=#FontColor#
FontSize=12
StringALign=LeftCenter

[SemiBoldText]
FontFace=#Font#
FontWeight=500
AntiAlias=1
FontColor=#FontColor#
FontSize=12
StringALign=LeftCenter

[RegularText]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=12
StringALign=LeftCenter
