[Variables]
@includeGlobal=#@#GlobalVars.inc
GlobalW=(640*#Scale#)
GlobalH=(864*#Scale#)
BoxW=(110*#scale#)

Location=Center
ShowSec=1
OnOff=1
Animated=1


;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝


[BoldText]
FontFace=#Font#
FontWeight=800
AntiAlias=1
FontColor=#FontColor#
FontSize=(12*#Scale#)
SolidColor=0,0,0,1

[SemiBoldText]
FontFace=#Font#
FontWeight=500
AntiAlias=1
FontColor=#FontColor#
FontSize=(12*#Scale#)
SolidColor=0,0,0,1

[RegularText]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=(12*#Scale#)
SolidColor=0,0,0,1
