[Variables]
@includeGlobal=#@#GlobalVars.inc
GlobalW=(593*#Scale#)
GlobalH=(864*#Scale#)
BoxW=(100*#scale#)
MonW=(120*#scale#)
SliderM=(70*#Scale#)
SliderX=#SliderM#
SliderW=(280*#Scale#)
SliderH=(3*#Scale#)

Location=Center
ShowSec=1
OnOff=1
Animated=1

Monitor=3

;;╔══════════════════════════════════════════════════════════════════════════════════════════════════════╗
;;║ METERSTYLES                                                                                          ║
;;╚══════════════════════════════════════════════════════════════════════════════════════════════════════╝


[BoldText]
FontFace=#Font#
FontWeight=800
AntiAlias=1
FontColor=#FontColor#
FontSize=(12*#Scale#)
SolidColor=0,0,0,1

[SemiBoldText]
FontFace=#Font#
FontWeight=500
AntiAlias=1
FontColor=#FontColor#
FontSize=(12*#Scale#)
SolidColor=0,0,0,1

[RegularText]
FontFace=#Font#
AntiAlias=1
FontColor=#FontColor#
FontSize=(12*#Scale#)
SolidColor=0,0,0,1
